// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Negocios_API.Datos;

#nullable disable

namespace NegociosAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240215222303_FeedTables")]
    partial class FeedTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Negocios_API.Models.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("RUC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Linda Vista",
                            FechaActualizacion = new DateTime(2024, 2, 15, 16, 23, 3, 713, DateTimeKind.Local).AddTicks(695),
                            FechaCreacion = new DateTime(2024, 2, 15, 16, 23, 3, 713, DateTimeKind.Local).AddTicks(694),
                            NombreNegocio = "Capri",
                            OwnerId = 1,
                            RUC = 123456789
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Bolonia",
                            FechaActualizacion = new DateTime(2024, 2, 15, 16, 23, 3, 713, DateTimeKind.Local).AddTicks(697),
                            FechaCreacion = new DateTime(2024, 2, 15, 16, 23, 3, 713, DateTimeKind.Local).AddTicks(697),
                            NombreNegocio = "Serta",
                            OwnerId = 1,
                            RUC = 11223344
                        });
                });

            modelBuilder.Entity("Negocios_API.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePropietario")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clave = "abcd1234",
                            Correo = "josephpineda1210@gmail.com",
                            FechaActualizacion = new DateTime(2024, 2, 15, 16, 23, 3, 713, DateTimeKind.Local).AddTicks(615),
                            FechaCreacion = new DateTime(2024, 2, 15, 16, 23, 3, 713, DateTimeKind.Local).AddTicks(606),
                            NombrePropietario = "Joseph Enmanuel Pineda Aguilera"
                        });
                });

            modelBuilder.Entity("Negocios_API.Models.Business", b =>
                {
                    b.HasOne("Negocios_API.Models.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
